Fixed race condition
-> when waiting the script would terminate when
if docker couldn't find the backend. added the
classic 2>/dev/null so it doesn't crash when
looping.

diff --git a/.github/workflows/docker-build-test.yml b/.github/workflows/docker-build-test.yml
--- a/.github/workflows/docker-build-test.yml
+++ b/.github/workflows/docker-build-test.yml
@@ -59,7 +59,10 @@ jobs:
         run: |
             # Wait and check
             for i in {1..50}; do
-            STATUS=$(docker inspect --format "{{.State.Health.Status}}" backend-ubuntu-vm-1)
+            STATUS=$(docker inspect --format "{{.State.Health.Status}}" backend_ubuntu-vm-1 2>/dev/null || echo "waiting")
+            if [ "$STATUS" == "No such object: backend-ubuntu-vm-1"];
+                then echo "Could not find backend... waiting..."
+            fi
             if [ "$STATUS" == "healthy" ]; 
                 then break; 
             fi
@@ -74,7 +77,10 @@ jobs:
         run: |
             # Wait and check
             for i in {1..50}; do
-            STATUS=$(docker inspect --format "{{.State.Health.Status}}" backend-powersync-1)
+            STATUS=$(docker inspect --format "{{.State.Health.Status}}" backend-powersync-1 2>/dev/null || echo "waiting")
+            if [ "$STATUS" == "No such object: backend-powersync-1"];
+                then echo "Could not find backend... waiting..."
+            fi
             if [ "$STATUS" == "healthy" ]; then break; fi
             if [ "$STATUS" == "unhealthy" ]; then 
                 echo "Powersync is in a bad state!"; 
