Added comments for junit and moved artifact upload
-> Changed artifact upload to be before the test report in
case of failure.
-> Added comments for junitreport.

diff --git a/.github/workflows/flutter.yml b/.github/workflows/flutter.yml
--- a/.github/workflows/flutter.yml
+++ b/.github/workflows/flutter.yml
@@ -53,7 +53,7 @@ jobs:
       - name: Set Timestamp
         run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
       
-
+      # Junit report convert flutter's json test report to jUnit
       - name: Flutter add junitreport
         run: flutter pub global activate junitreport
         working-directory: ./frontend/search_cms
@@ -65,13 +65,6 @@ jobs:
           flutter test --machine | tojunit --output test-results/flutter_report_${{ env.TIMESTAMP }}.xml
         working-directory: ./frontend/search_cms
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v6
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: 'frontend/search_cms/test-results/flutter_report_${{ env.TIMESTAMP }}.xml'
-          include_passed: True
-          fail_on_failure: True
       # Upload out flutter test to the artifacts
       - uses: actions/upload-artifact@v4
         with:
@@ -79,5 +72,14 @@ jobs:
           # Optional. Default is 'artifact'
           name: flutter_report_${{ env.TIMESTAMP }}
           path: frontend/search_cms/test-results/flutter_report_${{ env.TIMESTAMP }}.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'frontend/search_cms/test-results/flutter_report_${{ env.TIMESTAMP }}.xml'
+          include_passed: True
+          fail_on_failure: True
+      
           
       
