Add test report generation to integration tests
-> Added a test report to the integration test as well artifact uploading.

diff --git a/.github/workflows/flutter-integration.yml b/.github/workflows/flutter-integration.yml
--- a/.github/workflows/flutter-integration.yml
+++ b/.github/workflows/flutter-integration.yml
@@ -67,13 +67,39 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y xvfb x11-xserver-utils
           sudo apt-get install -y cmake ninja-build clang libgtk-3-dev
+
+      - name: Set Timestamp
+        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
+      
+
+      # Adding junitreport to convert json test result to jUnit.
+      - name: Flutter add junitreport
+        run: flutter pub global activate junitreport
+        working-directory: ./frontend/search_cms
         
       # runa headless xvfb to initiate flutter integration tests
       - name: Run headless test
         uses: coactions/setup-xvfb@v1
         with:
-          run: flutter test integration_test -d linux
+          run: flutter test integration_test -d linux | tojunit --output test-results/flutter_report_int_test_${{ env.TIMESTAMP }}.xml
           working-directory: ./frontend/search_cms
         env:
           API_BASE_URL: http://localhost:8080
       # Run integration tests in headless Chrom
+
+      # Upload Test reports to the pull request.
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'frontend/search_cms/test-results/flutter_report_int_test_${{ env.TIMESTAMP }}.xml'
+          include_passed: True
+          fail_on_failure: True
+
+      # Upload out flutter test to the artifacts
+      - uses: actions/upload-artifact@v4
+        with:
+          # Name of the artifact to upload.
+          # Optional. Default is 'artifact'
+          name: flutter_report_int_test_${{ env.TIMESTAMP }}
+          path: frontend/search_cms/test-results/flutter_report_int_test_${{ env.TIMESTAMP }}.xml
